version: "3.8"
services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-signcare}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-signcarepass}
      POSTGRES_DB: ${POSTGRES_DB:-signcare_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: